version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: chat_system
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data


  go_app:
    build:
      context: ./chats
      dockerfile: Dockerfile
    container_name: go_service
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    
  rails_app:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: rails_service
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - elastic_search
    networks:
      - app_network
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=admin
      - DB_PASSWORD=admin
      - REDIS_URL=redis://redis:6379/1
      - RAILS_ENV=development
      - ELASTICSEARCH_URL=http://elastic_search:9200
    volumes:
      - ./core:/app

  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    container_name: elastic_search
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app_network

volumes:
  db_data:  
  redis_data:
  elastic_search_data:

networks:
  app_network:
