process_chat:
  cron: "*/1 * * * *"
  class: "ProcessChatsJob"
  
process_messages:
  cron: "*/1 * * * *"
  class: "ProcessMessagesJob"


aggregate_counts:
  cron: "*/1 * * * *"
  class: "ProcessAggregatedCountsJob"